# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

target 'KVLogLocal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift', '~> 4.1.1'
  pod 'SwiftyUserDefaults', '~> 3.0.0'
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON'

end
